"""create_initial_tables

Revision ID: 326cf0ad4802
Revises: 
Create Date: 2026-04-13 20:06:50.874900

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '326cf0ad4802'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clients',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('phone_number', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_clients_phone_number'), 'clients', ['phone_number'], unique=True)
    op.create_table('specialty_profiles',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('profession_type', sa.String(length=50), nullable=False),
    sa.Column('agent_persona', sa.Text(), nullable=False),
    sa.Column('intake_form_schema', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('escalation_triggers', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('chromadb_collection_name', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('conversations',
    sa.Column('session_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('client_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('specialty_profile_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('current_agent', sa.String(length=100), nullable=True),
    sa.Column('context_window', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('collected_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('escalation_reason', sa.String(length=255), nullable=True),
    sa.Column('last_activity_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['specialty_profile_id'], ['specialty_profiles.id'], ),
    sa.PrimaryKeyConstraint('session_id')
    )
    op.create_index(op.f('ix_conversations_client_id'), 'conversations', ['client_id'], unique=False)
    op.create_table('faq_entries',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('specialty_profile_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('answer', sa.Text(), nullable=False),
    sa.Column('tags', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['specialty_profile_id'], ['specialty_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_faq_entries_specialty_profile_id'), 'faq_entries', ['specialty_profile_id'], unique=False)
    op.create_table('professionals',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('specialty_profile_id', sa.UUID(as_uuid=False), nullable=False),
    sa.ForeignKeyConstraint(['specialty_profile_id'], ['specialty_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('professionals')
    op.drop_index(op.f('ix_faq_entries_specialty_profile_id'), table_name='faq_entries')
    op.drop_table('faq_entries')
    op.drop_index(op.f('ix_conversations_client_id'), table_name='conversations')
    op.drop_table('conversations')
    op.drop_table('specialty_profiles')
    op.drop_index(op.f('ix_clients_phone_number'), table_name='clients')
    op.drop_table('clients')
    # ### end Alembic commands ###
